### ISSUE TITLE
Come up with some fun and randomized discord statuses

### ISSUE THREAD

**Issue by Awkewainze** [Awkewainze/FriendBot#15]
As of right now, the bot only has
`Watching you`
as a status. Steal ToddBot's idea and have some fun with it by randomly rotating through some statuses.

**Comment by jamesaspence** [comment]
ooh ooh I got dis

**Comment by Awkewainze** [comment]
Could be fun to do some Halloween themed stuff too!

**Comment by jamesaspence** [comment]
https://github.com/Awkewainze/FriendBot/pull/18
